apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-docs
  labels:
    app: abc-docs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-docs
  template:
    metadata:
      labels:
        app: abc-docs
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: site
          image: ghcr.io/talaatharb/abc:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
